ninja libFreeRTOS.a
ninja libFreeRTOSApp.a
ninja libwrapperFreeRTOS.a

clajo@99-66248 build_idris2 % gsc -exe -cc-options -Wl,--gc-sections -cc-options -nostdlib -cc-options -Wno-implicit-function-declaration -ld-options "gcc:~/.idris2/idris2-0.2.1/lib/libidris2_support.a" Demo/ARM926ejs-GCC-Idris/CMakeFiles/demo-ARM926ejs-Idris.dir/init.c.obj Demo/ARM926ejs-GCC-Idris/CMakeFiles/demo-ARM926ejs-Idris.dir/main.c.obj Demo/ARM926ejs-GCC-Idris/CMakeFiles/demo-ARM926ejs-Idris.dir/muslc_string.c.obj Demo/ARM926ejs-GCC-Idris/CMakeFiles/demo-ARM926ejs-Idris.dir/print.c.obj Demo/ARM926ejs-GCC-Idris/CMakeFiles/demo-ARM926ejs-Idris.dir/receive.c.obj Demo/ARM926ejs-GCC-Idris/CMakeFiles/demo-ARM926ejs-Idris.dir/startup.s.obj Demo/ARM926ejs-GCC-Idris/CMakeFiles/demo-ARM926ejs-Idris.dir/__/__/Source/list.c.obj Demo/ARM926ejs-GCC-Idris/CMakeFiles/demo-ARM926ejs-Idris.dir/__/__/Source/portable/GCC/ARM926EJ-S/drivers/interrupt.c.obj Demo/ARM926ejs-GCC-Idris/CMakeFiles/demo-ARM926ejs-Idris.dir/__/__/Source/portable/GCC/ARM926EJ-S/drivers/timer.c.obj Demo/ARM926ejs-GCC-Idris/CMakeFiles/demo-ARM926ejs-Idris.dir/__/__/Source/portable/GCC/ARM926EJ-S/drivers/uart.c.obj Demo/ARM926ejs-GCC-Idris/CMakeFiles/demo-ARM926ejs-Idris.dir/__/__/Source/portable/GCC/ARM926EJ-S/port.c.obj Demo/ARM926ejs-GCC-Idris/CMakeFiles/demo-ARM926ejs-Idris.dir/__/__/Source/portable/GCC/ARM926EJ-S/portISR.c.obj Demo/ARM926ejs-GCC-Idris/CMakeFiles/demo-ARM926ejs-Idris.dir/__/__/Source/portable/MemMang/heap_4.c.obj Demo/ARM926ejs-GCC-Idris/CMakeFiles/demo-ARM926ejs-Idris.dir/__/__/Source/queue.c.obj Demo/ARM926ejs-GCC-Idris/CMakeFiles/demo-ARM926ejs-Idris.dir/__/__/Source/tasks.c.obj Demo/ARM926ejs-GCC-Idris/CMakeFiles/demo-ARM926ejs-Idris.dir/Idris/demo-ARM926ejs-Idris-main.c.obj -o Demo/ARM926ejs-GCC-Idris/demo-ARM926ejs-Idris -Wl,-T,/Users/clajo/Repos/OpenSource/FreeRTOS-community-ports/Demo/ARM926ejs-GCC-Idris/qemu.ld -L /usr/local/Caskroom/gcc-arm-embedded/9-2020-q2-update/gcc-arm-none-eabi-9-2020-q2-update/bin/../lib/gcc/arm-none-eabi/9.3.1  ./Demo/ARM926ejs-GCC-Idris/Idris/demo-ARM926ejs-Idris-main.c  && cd /Users/clajo/Repos/OpenSource/FreeRTOS-community-ports/build_idris2/Demo/ARM926ejs-GCC-Idris && arm-none-eabi-objcopy -O binary demo-ARM926ejs-Idris /Users/clajo/Repos/OpenSource/FreeRTOS-community-ports/build_idris2/images/demo-ARM926ejs-Idris.bin                       


clajo@99-66248 build_idris2 % gsc -exe -cc-options "-Wl,-T,/Users/clajo/Repos/OpenSource/FreeRTOS-community-ports/Demo/ARM926ejs-GCC-Idris/qemu.ld" -cc-options "-L /usr/local/Caskroom/gcc-arm-embedded/9-2020-q2-update/gcc-arm-none-eabi-9-2020-q2-update/bin/../lib/gcc/arm-none-eabi/9.3.1" -cc-options -Wl,--gc-sections -cc-options -nostdlib -cc-options -Wno-implicit-function-declaration -ld-options "gcc:~/.idris2/idris2-0.2.1/lib/libidris2_support.a" Demo/ARM926ejs-GCC-Idris/CMakeFiles/demo-ARM926ejs-Idris.dir/init.c.obj Demo/ARM926ejs-GCC-Idris/CMakeFiles/demo-ARM926ejs-Idris.dir/main.c.obj Demo/ARM926ejs-GCC-Idris/CMakeFiles/demo-ARM926ejs-Idris.dir/muslc_string.c.obj Demo/ARM926ejs-GCC-Idris/CMakeFiles/demo-ARM926ejs-Idris.dir/print.c.obj Demo/ARM926ejs-GCC-Idris/CMakeFiles/demo-ARM926ejs-Idris.dir/receive.c.obj Demo/ARM926ejs-GCC-Idris/CMakeFiles/demo-ARM926ejs-Idris.dir/startup.s.obj Demo/ARM926ejs-GCC-Idris/CMakeFiles/demo-ARM926ejs-Idris.dir/__/__/Source/list.c.obj Demo/ARM926ejs-GCC-Idris/CMakeFiles/demo-ARM926ejs-Idris.dir/__/__/Source/portable/GCC/ARM926EJ-S/drivers/interrupt.c.obj Demo/ARM926ejs-GCC-Idris/CMakeFiles/demo-ARM926ejs-Idris.dir/__/__/Source/portable/GCC/ARM926EJ-S/drivers/timer.c.obj Demo/ARM926ejs-GCC-Idris/CMakeFiles/demo-ARM926ejs-Idris.dir/__/__/Source/portable/GCC/ARM926EJ-S/drivers/uart.c.obj Demo/ARM926ejs-GCC-Idris/CMakeFiles/demo-ARM926ejs-Idris.dir/__/__/Source/portable/GCC/ARM926EJ-S/port.c.obj Demo/ARM926ejs-GCC-Idris/CMakeFiles/demo-ARM926ejs-Idris.dir/__/__/Source/portable/GCC/ARM926EJ-S/portISR.c.obj Demo/ARM926ejs-GCC-Idris/CMakeFiles/demo-ARM926ejs-Idris.dir/__/__/Source/portable/MemMang/heap_4.c.obj Demo/ARM926ejs-GCC-Idris/CMakeFiles/demo-ARM926ejs-Idris.dir/__/__/Source/queue.c.obj Demo/ARM926ejs-GCC-Idris/CMakeFiles/demo-ARM926ejs-Idris.dir/__/__/Source/tasks.c.obj Demo/ARM926ejs-GCC-Idris/CMakeFiles/demo-ARM926ejs-Idris.dir/Idris/demo-ARM926ejs-Idris-main.c.obj -o Demo/ARM926ejs-GCC-Idris/demo-ARM926ejs-Idris ./Demo/ARM926ejs-GCC-Idris/Idris/demo-ARM926ejs-Idris-main.c  && cd /Users/clajo/Repos/OpenSource/FreeRTOS-community-ports/build_idris2/Demo/ARM926ejs-GCC-Idris && arm-none-eabi-objcopy -O binary demo-ARM926ejs-Idris /Users/clajo/Repos/OpenSource/FreeRTOS-community-ports/build_idris2/images/demo-ARM926ejs-Idris.bin

clajo@99-66248 build_idris2 % gsc -exe -cc-options "-Wl,-T,/Users/clajo/Repos/OpenSource/FreeRTOS-community-ports/Demo/ARM926ejs-GCC-Idris/qemu.ld" -cc-options "-L /usr/local/Caskroom/gcc-arm-embedded/9-2020-q2-update/gcc-arm-none-eabi-9-2020-q2-update/bin/../lib/gcc/arm-none-eabi/9.3.1" -cc-options -Wl,--gc-sections -cc-options -nostdlib -cc-options -Wno-implicit-function-declaration -ld-options "gcc:~/.idris2/idris2-0.2.1/lib/libidris2_support.a" -o Demo/ARM926ejs-GCC-Idris/demo-ARM926ejs-Idris ./Demo/ARM926ejs-GCC-Idris/Idris/demo-ARM926ejs-Idris-main.c  && cd /Users/clajo/Repos/OpenSource/FreeRTOS-community-ports/build_idris2/Demo/ARM926ejs-GCC-Idris && arm-none-eabi-objcopy -O binary demo-ARM926ejs-Idris /Users/clajo/Repos/OpenSource/FreeRTOS-community-ports/build_idris2/images/demo-ARM926ejs-Idris.bin

clajo@99-66248 build_idris2 % gsc -exe -cc-options "-Wl,-T,/Users/clajo/Repos/OpenSource/FreeRTOS-community-ports/Demo/ARM926ejs-GCC-Idris/qemu.ld" -cc-options "-L /usr/local/Caskroom/gcc-arm-embedded/9-2020-q2-update/gcc-arm-none-eabi-9-2020-q2-update/bin/../lib/gcc/arm-none-eabi/9.3.1" -cc-options -Wl,--gc-sections -cc-options -nostdlib -cc-options -Wno-implicit-function-declaration -ld-options "gcc:~/.idris2/idris2-0.2.1/lib/libidris2_support.a" -o Demo/ARM926ejs-GCC-Idris/demo-ARM926ejs-Idris ./Demo/ARM926ejs-GCC-Idris/Idris/demo-ARM926ejs-Idris-main.c                                                                                                        clang: warning: -Wl,-T,/Users/clajo/Repos/OpenSource/FreeRTOS-community-ports/Demo/ARM926ejs-GCC-Idris/qemu.ld: 'linker' input unused [-Wunused-command-line-argument]

clajo@99-66248 build_idris2 % /Users/clajo/Repos/OpenSource/Idris/gambit/gsc/gsc -exe -cc arm-none-eabi-gcc -cc-options "-Wl,-T,/Users/clajo/Repos/OpenSource/FreeRTOS-community-ports/Demo/ARM926ejs-GCC-Idris/qemu.ld" -cc-options "-L /usr/local/Caskroom/gcc-arm-embedded/9-2020-q2-update/gcc-arm-none-eabi-9-2020-q2-update/bin/../lib/gcc/arm-none-eabi/9.3.1" -cc-options -Wl,--gc-sections -cc-options -nostdlib -cc-options -Wno-implicit-function-declaration -ld-options ~/.idris2/idris2-0.2.1/lib/libidris2_support.a -o Demo/ARM926ejs-GCC-Idris/demo-ARM926ejs-Idris ./Demo/ARM926ejs-GCC-Idris/Idris/demo-ARM926ejs-Idris-main.c

/Users/clajo/Repos/OpenSource/Idris/gambit/gsc/gsc -exe -cc arm-none-eabi-gcc -cc-options "-Wl,-T,/Users/clajo/Repos/OpenSource/FreeRTOS-community-ports/Demo/ARM926ejs-GCC-Idris/qemu.ld" -cc-options "-L /usr/local/Caskroom/gcc-arm-embedded/9-2020-q2-update/gcc-arm-none-eabi-9-2020-q2-update/bin/../lib/gcc/arm-none-eabi/9.3.1" -cc-options -Wl,--gc-sections -cc-options -nostdlib -cc-options -Wno-implicit-function-declaration -ld-options ~/.idris2/idris2-0.2.1/lib/libidris2_support.a -ld-options libFreeRTOSApp.a -ld-options libFreeRTOS.a -o Demo/ARM926ejs-GCC-Idris/demo-ARM926ejs-Idris ./Demo/ARM926ejs-GCC-Idris/Idris/demo-ARM926ejs-Idris-main.c

/Users/clajo/Repos/OpenSource/Idris/gambit/gsc/gsc -exe -cc arm-none-eabi-gcc -cc-options "-Wl,-T,/Users/clajo/Repos/OpenSource/FreeRTOS-community-ports/Demo/ARM926ejs-GCC-Idris/qemu.ld" -cc-options "-L /usr/local/Caskroom/gcc-arm-embedded/9-2020-q2-update/gcc-arm-none-eabi-9-2020-q2-update/bin/../lib/gcc/arm-none-eabi/9.3.1" -cc-options -Wl,--gc-sections -cc-options -nostdlib -cc-options -Wno-implicit-function-declaration -ld-options ~/.idris2/idris2-0.2.1/lib/libidris2_support.a -ld-options libFreeRTOSApp.a -ld-options libFreeRTOS.a -ld-options libwrapperFreeRTOS.a -o Demo/ARM926ejs-GCC-Idris/demo-ARM926ejs-Idris ./Demo/ARM926ejs-GCC-Idris/Idris/demo-ARM926ejs-Idris-main.c

/Users/clajo/Repos/OpenSource/Idris/gambit/gsc/gsc -verbose -exe -cc arm-none-eabi-gcc -cc-options "-Wl,-T,/Users/clajo/Repos/OpenSource/FreeRTOS-community-ports/Demo/ARM926ejs-GCC-Idris/qemu.ld" -cc-options "-L /usr/local/Caskroom/gcc-arm-embedded/9-2020-q2-update/gcc-arm-none-eabi-9-2020-q2-update/bin/../lib/gcc/arm-none-eabi/9.3.1" -cc-options -Wl,--gc-sections -cc-options -nostdlib -cc-options -Wno-implicit-function-declaration -ld-options ~/.idris2/idris2-0.2.1/lib/libidris2_support.a -ld-options libFreeRTOSApp.a -ld-options libFreeRTOS.a -ld-options libwrapperFreeRTOS.a -o Demo/ARM926ejs-GCC-Idris/demo-ARM926ejs-Idris ./Demo/ARM926ejs-GCC-Idris/Idris/demo-ARM926ejs-Idris-main.c
